from pydantic import BaseModel
from typing import List


class Message(BaseModel):
    african: List[str | None]
    affenpinscher: List[str | None]
    african: List[str | None]
    airedale: List[str | None]
    akita: List[str | None]
    appenzeller: List[str | None]
    australian: List[str | None]
    basenji: List[str | None]
    beagle: List[str | None]
    bluetick: List[str | None]
    borzoi: List[str | None]
    bouvier: List[str | None]
    boxer: List[str | None]
    brabancon: List[str | None]
    briard: List[str | None]
    buhund: List[str | None]
    bulldog: List[str | None]
    bullterrier: List[str | None]
    cattledog: List[str | None]
    chihuahua: List[str | None]
    chow: List[str | None]
    clumber: List[str | None]
    cockapoo: List[str | None]
    collie: List[str | None]
    coonhound: List[str | None]
    corgi: List[str | None]
    cotondetulear: List[str | None]
    dachshund: List[str | None]
    dalmatian: List[str | None]
    dane: List[str | None]
    deerhound: List[str | None]
    dhole: List[str | None]
    dingo: List[str | None]
    doberman: List[str | None]
    elkhound: List[str | None]
    entlebucher: List[str | None]
    eskimo: List[str | None]
    finnish: List[str | None]
    frise: List[str | None]
    germanshepherd: List[str | None]
    greyhound: List[str | None]
    groenendael: List[str | None]
    havanese: List[str | None]
    hound: List[str | None]
    husky: List[str | None]
    keeshond: List[str | None]
    kelpie: List[str | None]
    komondor: List[str | None]
    kuvasz: List[str | None]
    labradoodle: List[str | None]
    labrador: List[str | None]
    leonberg: List[str | None]
    lhasa: List[str | None]
    malamute: List[str | None]
    malinois: List[str | None]
    maltese: List[str | None]
    mastiff: List[str | None]
    mexicanhairless: List[str | None]
    mix: List[str | None]
    mountain: List[str | None]
    newfoundland: List[str | None]
    otterhound: List[str | None]
    ovcharka: List[str | None]
    papillon: List[str | None]
    pekinese: List[str | None]
    pembroke: List[str | None]
    pinscher: List[str | None]
    pitbull: List[str | None]
    pointer: List[str | None]
    pomeranian: List[str | None]
    poodle: List[str | None]
    pug: List[str | None]
    puggle: List[str | None]
    pyrenees: List[str | None]
    redbone: List[str | None]
    retriever: List[str | None]
    ridgeback: List[str | None]
    rottweiler: List[str | None]
    saluki: List[str | None]
    samoyed: List[str | None]
    schipperke: List[str | None]
    schnauzer: List[str | None]
    segugio: List[str | None]
    setter: List[str | None]
    sharpei: List[str | None]
    sheepdog: List[str | None]
    shiba: List[str | None]
    shihtzu: List[str | None]
    spaniel: List[str | None]
    spitz: List[str | None]
    springer: List[str | None]
    stbernard: List[str | None]
    terrier: List[str | None]
    tervuren: List[str | None]
    vizsla: List[str | None]
    waterdog: List[str | None]
    weimaraner: List[str | None]
    whippet: List[str | None]
    wolfhound: List[str | None]


class GetResponseDogModel(BaseModel):
    message: str
    status: str


class GetResponseListDogModel(BaseModel):
    message: list[str]
    status: str


class GetResponseListBreedsModel(BaseModel):
    message: Message
    status: str
